package csd230.lab1.entities;

import jakarta.persistence.*;
import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.HashSet;
import java.util.Set;

/**
 * Entity representing a completed purchase.
 * It works as a snapshot of the cart at checkout time: which products were bought,
 * when, and how much was paid in total.
 */
@Entity
// Table name set explicitly because "order" is a reserved word in SQL
@Table(name = "orders")
public class OrderEntity implements Serializable {

    // Primary key, generated by the database (auto-increment column in MySQL)
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // Final price of the order. It is calculated once at checkout and stored,
    // so later price changes on a product do not rewrite old orders.
    private double totalAmount;

    // LocalDateTime instead of Date, as the lab asks.
    // @Temporal was removed because it only applies to java.util.Date and
    // causes a mapping error when used with LocalDateTime.
    private LocalDateTime orderDate;

    // Many orders can contain the same product and an order can contain many products,
    // so this is a many-to-many relationship. The order owns the join table below.
    // EAGER: the products are loaded together with the order, so the confirmation
    // page can list them without extra queries.
    // PERSIST and MERGE cascade the save operation to the related products.
    @ManyToMany(fetch = FetchType.EAGER, cascade = {CascadeType.PERSIST, CascadeType.MERGE})
    @JoinTable(
            name = "order_products",                                // join table created by Hibernate
            joinColumns = @JoinColumn(name = "order_id"),           // column pointing to this order
            inverseJoinColumns = @JoinColumn(name = "product_id")   // column pointing to each product
    )
    // Set instead of List: the same product cannot appear twice in one order
    private Set<ProductEntity> products = new HashSet<>();

    // No-args constructor required by JPA
    public OrderEntity() {
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public double getTotalAmount() {
        return totalAmount;
    }

    public void setTotalAmount(double totalAmount) {
        this.totalAmount = totalAmount;
    }

    public LocalDateTime getOrderDate() {
        return orderDate;
    }

    public void setOrderDate(LocalDateTime orderDate) {
        this.orderDate = orderDate;
    }

    public Set<ProductEntity> getProducts() {
        return products;
    }

    public void setProducts(Set<ProductEntity> products) {
        this.products = products;
    }

    // Convenience helper, same idea as CartEntity.addProduct()
    public void addProduct(ProductEntity product) {
        this.products.add(product);
    }
}